import os
import logging
from pathlib import Path
from datetime import datetime

def update_dashboard():
    """
    Updates Dashboard.md with current system status and folder counts.
    """
    # Use absolute path to ensure reliability across watchers
    vault_base = Path(__file__).parent.absolute()
    dashboard_path = vault_base / "Dashboard.md"
    
    # Folders to count
    folders = {
        "Needs Action": vault_base / "Needs_Action",
        "Pending Approval": vault_base / "Pending_Approval",
        "Approved": vault_base / "Approved",
        "Done": vault_base / "Done",
        "Inbox": vault_base / "Inbox"
    }
    
    counts = {}
    for name, path in folders.items():
        if path.exists():
            # Count only files, ignoring hidden ones
            count = len([f for f in path.iterdir() if f.is_file() and not f.name.startswith('.')])
        else:
            count = 0
        counts[name] = count

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    content = f"""---
last_updated: {timestamp}
status: active
---

# 🤖 AI Employee Dashboard

> **Live Status**: 🟢 Online | **Last Updated**: {timestamp}

---

## 📊 Quick Stats

| Folder | Count |
|--------|-------|
| 📂 Inbox | {counts['Inbox']} |
| 📬 Needs Action | {counts['Needs Action']} |
| ⏳ Pending Approval | {counts['Pending Approval']} |
| ✅ Approved | {counts['Approved']} |
| 🎉 Done | {counts['Done']} |

---

## 📅 Recent System Activity

- **[{timestamp}]** Dashboard refreshed.
- **[System]** All watchers operational.

---

*Generated by AI Employee System*
"""
    try:
        dashboard_path.write_text(content, encoding='utf-8')
        logging.info("Dashboard.md updated successfully.")
    except Exception as e:
        logging.error(f"Failed to update dashboard: {e}")

if __name__ == "__main__":
    # Test update
    logging.basicConfig(level=logging.INFO)
    update_dashboard()
